/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/textures/Hywirl.gltf -o src/components/Model/Hywirl.jsx -r public 
*/

import  { useRef,useEffect } from 'react'

import { useGLTF, useAnimations } from '@react-three/drei'

export function Hywirl(props:any) {
  const group = useRef()
  const { nodes, materials, animations }:any = useGLTF('/textures/Hywirl.gltf')
  const { actions }:any = useAnimations(animations, group)
  useEffect(()=>{
    actions["Flying_Idle"].reset().fadeIn(.5).play();
    return ()=>actions["Flying_idle"].fadeOut(.5)
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Hywirl">
            <skinnedMesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.Hywirl_Main} skeleton={nodes.Sphere.skeleton} />
            <skinnedMesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={materials.Eye_Black} skeleton={nodes.Sphere_1.skeleton} />
            <skinnedMesh name="Sphere_2" geometry={nodes.Sphere_2.geometry} material={materials.Eye_White} skeleton={nodes.Sphere_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/textures/Hywirl.gltf')
